refactored project structure, updated dependencies, replaced ESLint configuration, and improved workflow

diff --git a/.github/workflows/publish.yaml b/.github/workflows/publish.yaml
--- a/.github/workflows/publish.yaml
+++ b/.github/workflows/publish.yaml
@@ -1,20 +1,110 @@
 name: Publish package to GitHub Packages
 on:
   workflow_dispatch:
-  release:
-    types: [created]
+    inputs:
+      tag:
+        description: 'Tag to be created'
+        required: true
+
+  push:
+    tags:
+      - 'v*'
+
+permissions:
+  contents: write
+
 jobs:
-  publish:
+  prepare:
     runs-on: ubuntu-latest
+    outputs:
+      TAG: ${{ steps.set-output.outputs.TAG }}
     steps:
-      - uses: actions/checkout@v3
-      - uses: actions/setup-node@v3
+      - name: Set envs from inputs
+        if: ${{ github.event.inputs.tag != '' && ! startsWith(github.ref, 'refs/tags/') }}
+        run: echo "TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
+      - name: Set envs from metadata
+        if: ${{ github.event.inputs.tag == '' && startsWith(github.ref, 'refs/tags/') }}
+        run: echo "TAG=${{ github.ref }}" >> $GITHUB_ENV
+      - name: Set output
+        id: set-output
+        run: echo "TAG=${{ env.TAG }}" >> $GITHUB_OUTPUT
+
+  tag:
+    name: Create Tag
+    runs-on: ubuntu-latest
+    needs: prepare
+    if: ${{ github.event.inputs.tag != '' && ! startsWith(github.ref, 'refs/tags/') }}
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v4
+
+      - name: Validate Input Tag
+        run: |
+          if [[ ! "${{ github.event.inputs.tag }}" =~ ^v[0-9]+(\.[0-9]+)*-?.*$ ]]; then
+            echo "Invalid tag format. Use semantic versioning (e.g., v1.0.0)."
+            exit 1
+          fi
+          echo "Valid tag: ${{ github.event.inputs.tag }}"
+
+      - name: Create New Tag
+        env:
+          GH_TOKEN: ${{ github.token }}
+        run: |
+          # Create and push the tag
+          gh release create "${{github.needs.prepare.outputs.TAG}}" --title "Release ${{github.needs.prepare.outputs.TAG}}" --notes "Automated release for ${{github.needs.prepare.outputs.TAG}}"
+
+
+  release:
+    name: Create Release
+    runs-on: ubuntu-latest
+    needs: [prepare, tag]
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Setup Node.js
+        uses: actions/setup-node@v4
         with:
-          node-version: '16.x'
-          registry-url: 'https://registry.npmjs.org'
-          cache: 'npm'
+          node-version: '22.x'
+
+      - name: Install dependencies
+        run: npm ci
+
+      - name: Build package
+        run: npm run build
+
+      - name: Create package tarball
+        run: npm pack
+
+      - name: Release
+        uses: softprops/action-gh-release@v2
+        with:
+          tag_name: ${{ needs.prepare.outputs.TAG }}
+          name: Release ${{ needs.prepare.outputs.TAG }}
+          draft: false
+          prerelease: false
+          token: ${{ secrets.GH_PAT }}
+          repository: '${{ github.context.repo.owner }}/${{ github.context.repo.repo }}'
+          files: '*.tgz'
+
+  publish:
+    name: Publish Package
+    runs-on: ubuntu-latest
+    needs: prepare
+    permissions:
+      contents: read
+      packages: write
+    steps:
+      - uses: actions/checkout@v4
+      # Setup .npmrc file to publish to GitHub Packages
+      - uses: actions/setup-node@v4
+        with:
+          node-version: '22.x'
+          registry-url: 'https://npm.pkg.github.com'
+          # Defaults to the user or organization that owns the workflow file
+          scope: '@ofrules'
       - run: npm ci
       - run: npm run build
-      - run: npm publish --access public
+      - run: npm publish
         env:
-          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
+          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
